api_configs:
  openai:
    name: "OpenAI API"
    base_url: "https://api.openai.com/v1"
    endpoints:
      chat: "/chat/completions"
    headers:
      Authorization: "Bearer {api_key}"
      Content-Type: "application/json"
    request_format:
      model: "gpt-3.5-turbo"
      messages:
        - role: "user"
          content: "{prompt}"
      max_tokens: 1000
      temperature: 0.7

  azure_openai:
    name: "Azure OpenAI"
    base_url: "https://{resource_name}.openai.azure.com"
    endpoints:
      chat: "/openai/deployments/{deployment_name}/chat/completions?api-version=2023-12-01-preview"
    headers:
      api-key: "{api_key}"
      Content-Type: "application/json"
    request_format:
      messages:
        - role: "user"
          content: "{prompt}"
      max_tokens: 1000
      temperature: 0.7

  claude:
    name: "Anthropic Claude"
    base_url: "https://api.anthropic.com"
    endpoints:
      chat: "/v1/messages"
    headers:
      x-api-key: "{api_key}"
      anthropic-version: "2023-06-01"
      Content-Type: "application/json"
    request_format:
      model: "claude-3-sonnet-20240229"
      max_tokens: 1000
      messages:
        - role: "user"
          content: "{prompt}"

  volcengine:
    name: "火山引擎大模型"
    base_url: "https://ark.cn-beijing.volces.com"
    endpoints:
      chat: "/api/v3/chat/completions"
    headers:
      Authorization: "Bearer {api_key}"
      Content-Type: "application/json"
    request_format:
      model: "doubao-seed-1-6-250615"
      messages:
        - role: "user"
          content: "{prompt}"
      max_tokens: 1000
      temperature: 0.7

test_configs:
  demo:
    name: "测试压力测试配置"
    concurrent_levels: [5, 10]
    requests_per_level: 10
    timeout: 600
    retry_count: 3
    ramp_up_time: 5
    cool_down_time: 5

  default:
    name: "默认压力测试配置"
    concurrent_levels: [1, 5, 10]
    requests_per_level: 20
    timeout: 600
    retry_count: 3
    ramp_up_time: 5
    cool_down_time: 10

  intensive:
    name: "高强度压力测试"
    concurrent_levels: [10, 25, 50, 100, 200]
    requests_per_level: 200
    timeout: 60
    retry_count: 2
    ramp_up_time: 10
    cool_down_time: 15

  volcengine_test:
    name: "火山引擎专项测试配置"
    concurrent_levels: [1, 3, 5, 10, 15]
    requests_per_level: 50
    timeout: 45
    retry_count: 3
    ramp_up_time: 3
    cool_down_time: 5
    api_specific_settings:
      rate_limit: 10  # 每秒最大请求数
      model_variants: ["ep-20241216163511-xhmnw", "ep-20241216163512-abcde"]  # 示例endpoint ids

monitoring:
  ping_interval: 5
  health_check_timeout: 10
  network_stats_interval: 1

reporting:
  output_formats: ["html", "pdf", "excel"]
  include_charts: true
  chart_types: ["line", "bar", "histogram", "heatmap"]

data:
  prompt_file: "data/prompts.jsonl"
  results_dir: "reports"
  database_file: "data/test_results.db"
